// ItemData.cs
// -----------------------------------------------------------------------------
// ScriptableObject describing one usable item. Mirrors SkillData architecture
// so items behave like "mini skills" — they reuse SkillEffectData[] for their
// effect list and route through the same SkillResolver effect dispatch.
//
// Authoring is data-driven via the ItemDataEditor custom inspector, which
// hides irrelevant fields per-effect (mirroring SkillDataEditor + the shared
// EffectsListDrawer used by both).
//
// Notion field mapping (Items DB):
//   Name              → itemName
//   Effect Text       → effectText (description)
//   Action Cost       → actionCostType (Action / FreeAction / ZeroCost)
//   Target            → primaryTargetMode
//   Damage            → effects[0].magnitude (designer authors via Effects)
//   Duration          → duration
//   Stackable         → stackable
//   Consumed On Use   → consumedOnUse
//   Category          → category (Pouch/PartyInventory/BrewedPotion)
//   Owner             → ownerCharacter (Pouch only)
//   Generated By      → generatedBy
//   Notes             → notes
//   Spec Status       → not stored — design metadata only
//
// Why not ItemID = direct asset reference: ItemID is the stable address space
// (mirrors ConditionID) so ItemInstance can serialize cleanly and GenerateItem
// effects/Brew/Forge subsystems can refer to items by enum ID without needing
// an SO reference.
// -----------------------------------------------------------------------------
using System.Text;
using UnityEngine;

namespace DarkSpire
{
    [CreateAssetMenu(fileName = "NewItem", menuName = "DarkSpire/Item")]
    public class ItemData : ScriptableObject
    {
        // NOTE: no [Header(...)] attributes — the custom ItemDataEditor owns
        // section layout (mirrors SkillData/SkillDataEditor).

        // ── Identity ────────────────────────────────────────────────────────
        [Tooltip("Stable enum address for this item. Used by ItemInstance and " +
                 "GenerateItem effects to reference items at runtime. Must be " +
                 "unique across the project — duplicates produce a warning in " +
                 "the inspector.")]
        public ItemID itemID = ItemID.None;

        public string itemName;

        [Tooltip("Plain-English effect description shown in the info panel " +
                 "tooltip. Plays the role of SkillData.description.")]
        [TextArea(2, 4)] public string effectText;

        [Tooltip("Small icon (24-32px) shown on the item button in the action " +
                 "submenu. Items DO have icons (skills don't) — this is what " +
                 "the player taps in the scrollable item list.")]
        public Sprite icon;

        [Tooltip("Optional wide artwork shown on the info panel banner. Falls " +
                 "back to Resources/UI/DefaultItemArtBanner if null.")]
        public Sprite artBanner;

        [Range(-1f, 1f)] public float bannerFocalY = 0f;
        [Range(-1f, 1f)] public float bannerFocalX = 0f;

        // ── Combat ──────────────────────────────────────────────────────────
        [Tooltip("Action / FreeAction / ZeroCost. ZeroCost bypasses both action " +
                 "and free-action gates — item is usable unlimited times per turn.")]
        public ItemActionCostType actionCostType = ItemActionCostType.Action;

        public TargetMode primaryTargetMode = TargetMode.Self;

        [Tooltip("Most items are AutoHit (no roll). Use AttackRoll for items " +
                 "that 'attack' a target with a roll, WilSave for items that " +
                 "force a save (e.g. mind-affecting potions).")]
        public SkillDiceRule diceRule = SkillDiceRule.AutoHit;

        public SkillEffectData[] effects;

        [Tooltip("How many separate targets the player picks per use. Default " +
                 "1 = all SingleEnemy/SingleAlly effects share that pick. >1 = " +
                 "multi-pick, each effect's targetPickIndex chooses which pick " +
                 "it uses.")]
        [Min(1)] public int targetPickCount = 1;

        // ── Inventory ───────────────────────────────────────────────────────
        public ItemCategory category = ItemCategory.PartyInventory;

        [Tooltip("Persistent = stays until used (default). Transient/Passing/" +
                 "Ethereal define expiry rules — only Persistent is honored at " +
                 "runtime today.")]
        public ItemDuration duration = ItemDuration.Persistent;

        [Tooltip("Whether the player can hold multiple copies as one stack with " +
                 "a charges count. Non-stackable items occupy a separate slot " +
                 "per copy.")]
        public bool stackable = false;

        [Tooltip("Whether the item is destroyed (or its charges decremented) " +
                 "on use. Default true.")]
        public bool consumedOnUse = true;

        [Tooltip("Pouch items only — which character owns this item. Pouch " +
                 "items are character-locked; only the owner can use them. " +
                 "Leave null for PartyInventory and BrewedPotion items.")]
        public CharacterData ownerCharacter;

        // ── Meta (design only) ──────────────────────────────────────────────
        [Tooltip("Free-text source description: Forge, Brew skills, dungeon " +
                 "chests, etc. Design metadata, no runtime use.")]
        public string generatedBy;

        [TextArea(2, 4)]
        [Tooltip("Edge cases, regen rules, persistence-through-death, " +
                 "balancing flags. Design metadata, no runtime use.")]
        public string notes;

        // ─────────────────────────────────────────────────────────────────────
        //  Art banner accessor — same pattern as SkillData.GetArtBanner
        // ─────────────────────────────────────────────────────────────────────
        private static Sprite _defaultArtBannerCache;
        private static bool _defaultArtBannerLoaded;

        public const string DefaultArtBannerResourcePath = "UI/DefaultItemArtBanner";

        public Sprite GetArtBanner()
        {
            if (artBanner != null) return artBanner;
            if (!_defaultArtBannerLoaded)
            {
                _defaultArtBannerCache = Resources.Load<Sprite>(DefaultArtBannerResourcePath);
                _defaultArtBannerLoaded = true;
            }
            return _defaultArtBannerCache;
        }

        // ─────────────────────────────────────────────────────────────────────
        //  Effect text auto-generation (mirrors SkillData.BuildDescription)
        // ─────────────────────────────────────────────────────────────────────
        //
        // Walks the effects array and produces a GDD-keyword-consistent
        // description. Same vocabulary as skills — items are mini-skills.
        // The custom editor shows this as a preview with a "Copy to Effect
        // Text" button.

        public string BuildEffectText()
        {
            if (effects == null || effects.Length == 0) return "";

            var sb = new StringBuilder();
            for (int i = 0; i < effects.Length; i++)
            {
                string clause = BuildEffectClause(effects[i]);
                if (string.IsNullOrEmpty(clause)) continue;
                if (sb.Length > 0) sb.Append(' ');
                sb.Append(clause);
            }
            return sb.ToString();
        }

        private string BuildEffectClause(SkillEffectData e)
        {
            string tgt = TargetPhrase(e.targetMode);

            switch (e.effectType)
            {
                case SkillEffectType.Attack:
                    string verb = diceRule == SkillDiceRule.AttackRoll ? "Attack" : "Deal";
                    return $"{verb} {tgt} for {DamageExpr(e)} damage.";

                case SkillEffectType.Apply:
                    return e.applyKind == ApplyKind.Damage
                        ? $"Deal {DamageExpr(e)} direct damage to {tgt}."
                        : BuildConditionClause(e, tgt, afflict: false);

                case SkillEffectType.Afflict:
                    return BuildConditionClause(e, tgt, afflict: true);

                case SkillEffectType.DirectDamage:
                    return $"Deal {DamageExpr(e)} direct damage to {tgt}.";

                case SkillEffectType.Heal:
                    return $"Heal {tgt} for {e.magnitude} HP.";

                case SkillEffectType.RestoreSP:
                    return $"Restore {e.magnitude} SP to {tgt}.";

                case SkillEffectType.ApplyCondition:
                    return BuildConditionClause(e, tgt, afflict: diceRule == SkillDiceRule.WilSave);

                case SkillEffectType.RemoveCondition:
                    return $"Remove {e.conditionID} from {tgt}.";

                case SkillEffectType.Move:
                    return BuildMoveClause(e);

                case SkillEffectType.LoseHP:
                    return $"Lose {e.magnitude} HP.";

                default: return "";
            }
        }

        private static string DamageExpr(SkillEffectData e) => e.damageStat switch
        {
            DamageStat.POW => $"{e.magnitude}+POW",
            DamageStat.DEX => $"{e.magnitude}+DEX",
            DamageStat.WIL => $"{e.magnitude}+WIL",
            _              => e.magnitude.ToString(),
        };

        private string BuildConditionClause(SkillEffectData e, string tgt, bool afflict)
        {
            string cond = e.conditionID.ToString();
            int n = e.conditionStacks > 0 ? e.conditionStacks : Mathf.Max(1, e.magnitude);
            int per = Mathf.Max(1, e.stackPer);

            string amount = e.stackCountKind switch
            {
                ConditionStackSource.Fixed => n.ToString(),
                ConditionStackSource.UnblockedDamage => $"{n} per {per} unblocked damage",
                ConditionStackSource.DamageDealt     => $"{n} per {per} damage dealt",
                ConditionStackSource.CasterPOW       => $"{n} per {per} POW",
                ConditionStackSource.TargetStacks    => $"{n} per {per} {cond} on target",
                _ => n.ToString(),
            };

            return afflict
                ? $"Afflict {tgt} to apply {amount} {cond}."
                : $"Apply {amount} {cond} to {tgt}.";
        }

        private string BuildMoveClause(SkillEffectData e)
        {
            string save = e.saveDC > 0 ? $" (WIL DC {e.saveDC} resists)" : "";
            return e.movementKind switch
            {
                MovementKind.Advance   => $"Advance {e.movementMagnitude}.",
                MovementKind.Withdraw  => $"Withdraw {e.movementMagnitude}.",
                MovementKind.Pull      => $"Pull {e.movementMagnitude}{save}.",
                MovementKind.Knockback => $"Knockback {e.movementMagnitude}{save}.",
                MovementKind.Shuffle   => $"Shuffle{save}.",
                _ => "",
            };
        }

        private static string TargetPhrase(TargetMode mode) => mode switch
        {
            TargetMode.SingleEnemy => "an enemy",
            TargetMode.AllEnemies  => "all enemies",
            TargetMode.RandomEnemy => "a random enemy",
            TargetMode.Self        => "yourself",
            TargetMode.SingleAlly  => "an ally",
            TargetMode.AllAllies   => "all allies",
            TargetMode.RandomAlly  => "a random ally",
            TargetMode.WholeParty  => "the whole party",
            _ => "a target",
        };
    }
}
